name: Build & Upload Release Asset
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag, e.g. v1.0.0"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with: 
          distribution: temurin
          java-version: 17
      
      - uses: android-actions/setup-android@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: App V2/package-lock.json

      - name: Install npm dependencies
        working-directory: App V2
        run: npm ci

      # Use Expo CLI to build instead of direct Gradle
      - name: Build APK with Expo CLI
        working-directory: App V2
        run: |
          # Prebuild to ensure Android project is properly configured
          npx expo prebuild --platform android --clear
          
          # Build using Expo's build system which handles module configuration
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon --max-workers=1 -x lintVitalAnalyzeRelease
        env:
          GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2048m -Dorg.gradle.daemon=false"

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            App V2/android/app/build/outputs/apk/release/app-release*.apk